---
{
   "kind": "pipeline",
   "name": "amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "environment": {
            "GITHUB_TOKEN": {
               "from_secret": "GITHUB_TOKEN"
            }
         },
         "image": "plugins/docker",
         "name": "build",
         "settings": {
            "build_args_from_env": [
               "GITHUB_TOKEN",
               "DRONE_BUILD_EVENT",
               "DRONE_REPO_OWNER",
               "DRONE_REPO_NAME",
               "DRONE_COMMIT_REF",
               "DRONE_STAGE_ARCH"
            ],
            "dry_run": true,
            "repo": "dqlite"
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "environment": {
            "GITHUB_TOKEN": {
               "from_secret": "GITHUB_TOKEN"
            }
         },
         "image": "plugins/docker",
         "name": "build",
         "settings": {
            "build_args_from_env": [
               "GITHUB_TOKEN",
               "DRONE_BUILD_EVENT",
               "DRONE_REPO_OWNER",
               "DRONE_REPO_NAME",
               "DRONE_COMMIT_REF",
               "DRONE_STAGE_ARCH"
            ],
            "dry_run": true,
            "repo": "dqlite"
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "arm",
   "platform": {
      "arch": "arm",
      "os": "linux"
   },
   "steps": [
      {
         "environment": {
            "GITHUB_TOKEN": {
               "from_secret": "GITHUB_TOKEN"
            }
         },
         "image": "plugins/docker",
         "name": "build",
         "settings": {
            "build_args_from_env": [
               "GITHUB_TOKEN",
               "DRONE_BUILD_EVENT",
               "DRONE_REPO_OWNER",
               "DRONE_REPO_NAME",
               "DRONE_COMMIT_REF",
               "DRONE_STAGE_ARCH"
            ],
            "dry_run": true,
            "repo": "dqlite"
         }
      }
   ]
}
...
